# Campus networks: users from these addresses are redirected straight to
# the provider (IP-based licence), the proxy is skipped.
geo $via_campus {
    default 0;
    # 192.0.2.0/24 1;
    # 2001:db8::/32 1;
}
